### ISSUE TITLE
Albums in state is updated without calling setAlbums

### ISSUE THREAD

**Issue by dmahely** [dmahely/artest#4]
Hello @tryggvigy, hope you're having a good one :) 
I'm doing a bit of a refactor and noticed this behavior. In `<RoundSelection />` I have this part which is calling `fetchArtistData`

```javascript
// RoundSelection.js

const albums = await fetchFiveRandomAlbums();
setAlbums({ albums });
const albumsWithArtistImages = await fetchArtistData(albums, currentRound);
setAlbums({albums: albumsWithArtistImages}); // commenting this out will update the state with albumsWithArtistImages regardless
```

and `fetchArtistData` has this snippet
```javascript
// fetchArtistData.js

albums.forEach((album, index) => {
        album.artistsArray[currentRound - 1].image = artistImages[index];
    });

return albums;
```

I know that forEach mutates the original array, but I don't understand why albums is updated in the state without me explicitly calling `setAlbums`.

**Comment by dmahely** [comment]
Not sure if these are related, but I'm having an issue where I'm setting the `albums` object in state in `<RoundSelection />` before changing the route to `<Round />` and passing `albums` there as well. However, I'm not able to access the `albums` object correctly in `<Round />`. Instead of having `albums` point to the object, in state I have an `albums` variable that has a property called `albums` that contains the object. Example log below 👇 I'm setting state via `setAlbums({albums: albumsWithRelatedArtists});`

<img width="514" alt="Screen Shot 2020-09-12 at 2 23 16 AM" src="https://user-images.githubusercontent.com/21047475/92977854-2a9b0000-f49f-11ea-86da-5833246b0a01.png">

**Comment by tryggvigy** [comment]
Hey Doaa,

You could do `setAlbums(albumsWithRelatedArtists);` to make the albums state be the array itself and avoid the extra object wrapper with an `albums` key.


What's the idea with setting the album state twice? It is to render faster?

> I know that forEach mutates the original array, but I don't understand why albums is updated in the state without me explicitly calling setAlbums.

forEach doesn't in itself modify the original array, but you are modifying it inside it. That could be causing the unexpected state update you are seeing. Maybe we can do something like this


```js
const albums = await fetchFiveRandomAlbums();
setAlbums({ albums });
const artistsIds = albums.map(round => round.artistsArray[currentRound - 1].id)
const artistsImages = await fetchArtistImages(artistIds);
setAlbums(albums => albums.map((album, index) => ({
   ...album,
   // update artistArray with the picture modified on item at index currentRound-1
   artistArray: [
     ...album.artistArray(0, currentRound - 1),
     {
       ...album.artistsArray[currentRound - 1],
       picture: artistsImages[index],
     },
     ...album.artistArray(currentRound - 1)
   ]
}));
```

You can see immutable update patterns in the redux docs. https://redux.js.org/recipes/structuring-reducers/immutable-update-patterns. this way we make sure to return a fresh object back to react.

As you can see this update is getting pretty complex. I'm wondering if we can hide more complexity in the API layer? What would be the ideal data for the UI to receive? Maybe we can patch everything up in a nice data object before handing any of the data back to React and the UI

**Comment by dmahely** [comment]
> You could do setAlbums(albumsWithRelatedArtists); to make the albums state be the array itself and avoid the extra object wrapper with an albums key.

I was banging my head for hours with this one. So my mistake was surrounding the variable with {} 🤦 

> What's the idea with setting the album state twice? It is to render faster?

Ha, no. That was just how I structured it when I was removing the API calls out of the components, setting the state after each call to test that it's working. I noticed how unnecessary it is now and wanted to remove it when I noticed that state is being updated anyway, even with all but the last `setState()` commented out.

> forEach doesn't in itself modify the original array, but you are modifying it inside it. That could be causing the unexpected state update you are seeing.

I did not fully understand your point here, but I will try out a couple of different things and let you know 👌 

> I'm wondering if we can hide more complexity in the API layer? What would be the ideal data for the UI to receive? Maybe we can patch everything up in a nice data object before handing any of the data back to React and the UI

I'm still refactoring and thought about this as well. I will do so and update you!

Thanks a lot!

**Comment by tryggvigy** [comment]
Yeah I'm not sure how helpful my comment about updating the state like this was :) Not sure if we even need to do anything like this. I think we can do most of the heavy lifting of fetching and massaging the data into the right format in the API layer.

> Ha, no. That was just how I structured it when I was removing the API calls out of the components, setting the state after each call to test that it's working. I noticed how unnecessary it is now and wanted to remove it when I noticed that state is being updated anyway, even with all but the last setState() commented out.

Ah! I think I actually know why 
```js
const albums = await fetchFiveRandomAlbums();
setAlbums({ albums });
const albumsWithArtistImages = await fetchArtistData(albums, currentRound);
setAlbums({albums: albumsWithArtistImages}); // commenting this out will update the state with albumsWithArtistImages regardless
```
you saw this ^ problem!

React `useState` is asynchronous and tends to batch updates together in an attempt to be more performant.
Because `albums` was being modified inside `await fetchArtistData(albums, currentRound);` it likely happened before React actually did the state update, resulting in the latest version of `albums` being the modified one.

This is actually a really good real world example of why it's often recommended to use immutable data with React.

**Comment by dmahely** [comment]
Ahh okay! I finally understood. I forgot that useState is async!
