### ISSUE TITLE
isAccessTokenValid fetches a new token internally.

### ISSUE THREAD

**Issue by tryggvigy** [dmahely/artest#6]
https://github.com/dmahely/artest/blob/master/src/components/App/App.js#L25-L28

`isAccessTokenValid` calls `fetchAccessToken` internally. I think it would be clearer if `isAccessTokenValid` would, like it's name suggests, check if the token is valid:

```js
// checks if an access token is valid by checking its expiry date against the current time
// returns true if more than 5 minutes are left for the access token
export const isAccessTokenValid = () => {
    const currentTokenExpiry = Number(localStorage.getItem('expiry'));
    const currentTime = Date.now();
    const differenceInMinutes =
        (currentTokenExpiry - currentTime) / (1000 * 60);

    if (differenceInMinutes > 5) return true;
    return false;
};
```

This follows the single responsibility principle nicely.

**Comment by dmahely** [comment]
That's right, it wasn't even needed apparently!
I refactored as you suggested in 8b8e6fc.

**Comment by tryggvigy** [comment]
nice!
