### ISSUE TITLE
Consistency in props use

### ISSUE THREAD

**Issue by tryggvigy** [dmahely/artest#8]
In some places the props are destructured into variables but then `props.xxx` is also used. For example https://github.com/dmahely/artest/blob/master/src/components/Artist/Artist.js#L16

I would suggest being consistent with this in components. I like to destructure the props in the function argument:

```js
const Artist = ({ setRoute, number, image, name, answer, setResults }) => {
```

but it doesn't matter much. Being consistent with it matters more :)

**Comment by dmahely** [comment]
That's a very neat style indeed! I refactored in the linked PR.
